[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "_THEPROJECT_"
version = "0.0.1"
authors = [
    { name="_THEUSER_", email="_THEEMAIL_" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]

[project.urls]
"Homepage" = "https://github.com/cionz0/_THEPROJECT_"
"Bug Tracker" = "https://github.com/cionz0/_THEPROJECT_/issues"

[tool.setuptools.packages.find]
where = ["src"]